version: "2"
services:
  db:
    image: sensebox/opensensemap-api-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      OSEM_dbhost: db
      OSEM_dbuser: senseboxapiuser
      OSEM_dbuserpass: userpass

volumes:
  mongodata:
